### ISSUE TITLE
Please use helm default property release namespace instead of a extra namespace property

### ISSUE THREAD

**Issue by bkSentinel** [emqx/emqx-chart#10]
I think you should use the helm integrated (helm)release namespace property instead of using the extra one defined in your values.yaml.

```
helm upgrade --install --devel emqx \
             --namespace emqx \
             emqx/emqx

```
Installing a application with helm this way would normaly lead to all resources placed into the right namespace. In the case of emqx all resources are created in the default namespace.

**Comment by Rory-Z** [comment]
@bkSentinel Thanks for your feedback, I have fixed it
