### ISSUE TITLE
Activation of EMQ-X modules

### ISSUE THREAD

**Issue by dealproc** [emqx/emqx-chart#2]
Can an example be provided on how we can properly configure the helm chart to allow the use of plugins for EMQ-X?  I'm specifically looking for how to use the username/password plugin against a MongoDB database; however, I believe that having something that may be slightly more generic in nature, or more encompassing, may be a better alternative.

Thanks.

**Comment by Rory-Z** [comment]
For how to configure the EMQ X plug-in, you can query the [docker images documentation](https://github.com/emqx/emqx-docker#emq-x-configuration) and configure it in `Values.emqxConfig`
