### ISSUE TITLE
Scale up cpu usage

### ISSUE THREAD

**Issue by lewisdiamond** [emqx/emqx-chart#4]
When scaling up an emqx deployment from the chart (haven't tested anything else), new instances take up 100% cpu on the host (1 full thread/core).
```
   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command          
 40883 ldiamond   20   0   760     8     0 R 98.8  0.0  0:56.65 erl_child_setup 1073741816 
```

**Comment by Rory-Z** [comment]
Sorry for replying so lately, please provide us with more information.

**Comment by Rory-Z** [comment]
This issue has not been updated for a long time, I will close it first, you can open it again at any time
